### ISSUE TITLE
Can't build on Ubuntu 16.04

### ISSUE THREAD

**Issue by emkman** [BeamMW/cuda-miner#1]
There seems to be conflicts regarding GCC versions. I tried to build with GCC 5 but it failed, so per your instructions I installed and aliases GCC 7. But now `make` gives me the following error:

>[ 76%] Built target beam
[ 78%] Building NVCC (Device) object equihash/cuda/CMakeFiles/equihash-cuda.dir/equihash-cuda_generated_CudaSolver.cu.o
In file included from /usr/local/cuda-9.1/include/host_config.h:50:0,
                 from /usr/local/cuda-9.1/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda-9.1/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
In file included from /home/prospector/beam-mining/beam-miner/cuda/cuda-miner/equihash/cuda/CudaSolver.cu:1:0:
/home/prospector/beam-mining/beam-miner/cuda/cuda-miner/equihash/cuda/CudaSolver-150-5-L.cuh:21:10: fatal error: base/Logging.hpp: No such file or directory
 #include "base/Logging.hpp"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at equihash-cuda_generated_CudaSolver.cu.o.cmake:207 (message):
  Error generating
  /home/prospector/beam-mining/beam-miner/cuda/cuda-miner/build/equihash/cuda/CMakeFiles/equihash-cuda.dir//./equihash-cuda_generated_CudaSolver.cu.o
equihash/cuda/CMakeFiles/equihash-cuda.dir/build.make:63: recipe for target 'equihash/cuda/CMakeFiles/equihash-cuda.dir/equihash-cuda_generated_CudaSolver.cu.o' failed
make[2]: *** [equihash/cuda/CMakeFiles/equihash-cuda.dir/equihash-cuda_generated_CudaSolver.cu.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'equihash/cuda/CMakeFiles/equihash-cuda.dir/all' failed
make[1]: *** [equihash/cuda/CMakeFiles/equihash-cuda.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

So another part of the build process seems to be complaining that GCC is > 6. How do these two requirements get resolved?

**Comment by emkman** [comment]
My cmake command was `cmake -DCMAKE_BUILD_TYPE=Release -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.1 .` and my Nvidia drivers are `390.25`

**Comment by kccheung** [comment]
I am having similar problem. Did you able to resolve this?

**Comment by emkman** [comment]
@kccheung No put they are providing pre-built binaries on the Releases tab now so I haven't needed to build. I have also switched back to the OpenCL miner until https://github.com/BeamMW/cuda-miner/issues/5 is resolved.
